const { spawn } = require("node:child_process");
const fs = require("node:fs");
const http = require("node:http");
const net = require("node:net");
const os = require("node:os");
const path = require("node:path");

function clampPort(n, fallback) {
  const v = Number(n);
  if (!Number.isFinite(v) || v <= 0) return fallback;
  return Math.min(65535, Math.max(1024, Math.trunc(v)));
}

function defaultUserDataDir() {
  const base =
    String(process.env.LOCALAPPDATA ?? "").trim() ||
    String(process.env.APPDATA ?? "").trim() ||
    os.homedir();
  return path.join(base, "TouhouTalkDesktopDev");
}

function ensureEnvTemplate(envPath) {
  if (fs.existsSync(envPath)) return;
  const tpl = [
    "# Touhou Talk Desktop env (dev local only)",
    "",
    "# Supabase",
    "NEXT_PUBLIC_SUPABASE_URL=",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=",
    "SUPABASE_SERVICE_ROLE_KEY=",
    "",
    "# Backend Persona OS URL (FastAPI / gensokyo-persona-core)",
    "SIGMARIS_CORE_URL=http://127.0.0.1:8000",
    "",
    "# Optional: force port",
    "TOUHOU_DESKTOP_PORT=3789",
    "",
  ].join("\n");
  fs.mkdirSync(path.dirname(envPath), { recursive: true });
  fs.writeFileSync(envPath, tpl, "utf8");
}

function readEnvFile(p) {
  try {
    const txt = fs.readFileSync(p, "utf8");
    const out = {};
    for (const line of txt.split(/\r?\n/)) {
      const s = line.trim();
      if (!s || s.startsWith("#")) continue;
      const i = s.indexOf("=");
      if (i <= 0) continue;
      const k = s.slice(0, i).trim();
      const v = s.slice(i + 1).trim();
      if (!k) continue;
      out[k] = v;
    }
    return out;
  } catch {
    return null;
  }
}

function pickNonEmpty(vars, key) {
  const v = vars && typeof vars[key] === "string" ? String(vars[key]).trim() : "";
  return v || "";
}

function readFirstExisting(paths) {
  for (const p of paths) {
    try {
      if (fs.existsSync(p)) return readEnvFile(p);
    } catch {}
  }
  return null;
}

function waitForHttpOk(url, timeoutMs) {
  const startedAt = Date.now();
  return new Promise((resolve) => {
    const tick = () => {
      const req = http.get(url, (res) => {
        res.resume();
        resolve(res.statusCode && res.statusCode >= 200 && res.statusCode < 500);
      });
      req.on("error", () => {
        if (Date.now() - startedAt > timeoutMs) return resolve(false);
        setTimeout(tick, 300);
      });
      req.setTimeout(1500, () => req.destroy());
    };
    tick();
  });
}

function resolveElectronBin(projectRoot) {
  // `require("electron")` returns the platform-specific executable path when run in Node.
  try {
    const p = require("electron");
    if (typeof p === "string" && p.trim()) return p.trim();
  } catch {}

  // Fallback: npm .bin (may require `shell: true` on Windows in some setups)
  if (process.platform === "win32") return path.join(projectRoot, "node_modules", ".bin", "electron.cmd");
  return path.join(projectRoot, "node_modules", ".bin", "electron");
}

function bundleDefaultEnvPath(projectRoot) {
  // dev: tools/desktop/.bundle/default.env (generated by desktop:prepare)
  return path.join(projectRoot, "tools", "desktop", ".bundle", "default.env");
}

function isPortFreeOnHost(port, host) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.unref();
    server.once("error", (e) => {
      if (e && (e.code === "EADDRINUSE" || e.code === "EACCES")) return resolve(false);
      return resolve(false);
    });
    server.listen({ port, host, exclusive: true }, () => {
      server.close(() => resolve(true));
    });
  });
}

async function isPortFree(port) {
  // Next on Windows often binds to `::` (dual-stack). Check both to avoid false positives.
  const okV6 = await isPortFreeOnHost(port, "::").catch(() => false);
  if (!okV6) return false;
  const okV4 = await isPortFreeOnHost(port, "127.0.0.1").catch(() => false);
  return okV4;
}

async function findFreePort(startPort, maxTries = 50) {
  const start = clampPort(startPort, 3000);
  for (let i = 0; i < maxTries; i += 1) {
    const p = start + i;
    // Stay in non-privileged range.
    if (p > 65535) break;
    // eslint-disable-next-line no-await-in-loop
    if (await isPortFree(p)) return p;
  }
  throw new Error(`[desktop:dev] No free port found starting at ${start} (tried ${maxTries} ports)`);
}

async function main() {
  const projectRoot = path.resolve(__dirname, "..", "..");
  const devScript = path.join(projectRoot, "tools", "dev.mjs");
  const electronMain = path.join(projectRoot, "tools", "desktop", "main.cjs");
  const electronBin = resolveElectronBin(projectRoot);

  const requestedPort = process.env.TOUHOU_DESKTOP_DEV_PORT ?? process.env.PORT ?? 3000;
  const port = await findFreePort(requestedPort, 60);
  if (Number(requestedPort) !== port) {
    console.log(`[desktop:dev] Port ${requestedPort} is in use; using ${port}`);
  }
  const userDataDir = String(process.env.TOUHOU_DESKTOP_USERDATA_DIR ?? "").trim() || defaultUserDataDir();
  const envPath =
    String(process.env.TOUHOU_DESKTOP_ENV_PATH ?? "").trim() || path.join(userDataDir, "touhou-talk.env");

  fs.mkdirSync(userDataDir, { recursive: true });
  ensureEnvTemplate(envPath);

  const defaultVars = readEnvFile(bundleDefaultEnvPath(projectRoot)) || {};
  const fileVars = readEnvFile(envPath) || {};
  const repoRoot = path.resolve(projectRoot, "..");
  const repoEnv =
    readFirstExisting([path.join(repoRoot, ".env.local"), path.join(repoRoot, ".env")]) || {};
  const appEnv =
    readFirstExisting([path.join(projectRoot, ".env.local"), path.join(projectRoot, ".env")]) || {};

  // Merge public / server config from desktop env file into process env for Next dev.
  // This is critical because middleware + client bundle read env at compile time in dev.
  // Safety: never propagate service role keys from disk.
  const mergedEnv = { ...process.env };
  const nextPublicUrl =
    pickNonEmpty(defaultVars, "NEXT_PUBLIC_SUPABASE_URL") ||
    pickNonEmpty(defaultVars, "SUPABASE_URL") ||
    pickNonEmpty(fileVars, "NEXT_PUBLIC_SUPABASE_URL") ||
    pickNonEmpty(fileVars, "SUPABASE_URL") ||
    pickNonEmpty(appEnv, "NEXT_PUBLIC_SUPABASE_URL") ||
    pickNonEmpty(appEnv, "SUPABASE_URL") ||
    pickNonEmpty(repoEnv, "NEXT_PUBLIC_SUPABASE_URL") ||
    pickNonEmpty(repoEnv, "SUPABASE_URL");
  const nextPublicAnon =
    pickNonEmpty(defaultVars, "NEXT_PUBLIC_SUPABASE_ANON_KEY") ||
    pickNonEmpty(defaultVars, "SUPABASE_ANON_KEY") ||
    pickNonEmpty(fileVars, "NEXT_PUBLIC_SUPABASE_ANON_KEY") ||
    pickNonEmpty(fileVars, "SUPABASE_ANON_KEY") ||
    pickNonEmpty(appEnv, "NEXT_PUBLIC_SUPABASE_ANON_KEY") ||
    pickNonEmpty(appEnv, "SUPABASE_ANON_KEY") ||
    pickNonEmpty(repoEnv, "NEXT_PUBLIC_SUPABASE_ANON_KEY") ||
    pickNonEmpty(repoEnv, "SUPABASE_ANON_KEY");

  if (nextPublicUrl) mergedEnv.NEXT_PUBLIC_SUPABASE_URL = nextPublicUrl;
  if (nextPublicAnon) mergedEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY = nextPublicAnon;

  const supabaseUrl =
    pickNonEmpty(defaultVars, "SUPABASE_URL") ||
    pickNonEmpty(fileVars, "SUPABASE_URL") ||
    pickNonEmpty(appEnv, "SUPABASE_URL") ||
    pickNonEmpty(repoEnv, "SUPABASE_URL");
  const supabaseAnon =
    pickNonEmpty(defaultVars, "SUPABASE_ANON_KEY") ||
    pickNonEmpty(fileVars, "SUPABASE_ANON_KEY") ||
    pickNonEmpty(appEnv, "SUPABASE_ANON_KEY") ||
    pickNonEmpty(repoEnv, "SUPABASE_ANON_KEY");
  const coreUrl =
    pickNonEmpty(defaultVars, "SIGMARIS_CORE_URL") ||
    pickNonEmpty(fileVars, "SIGMARIS_CORE_URL") ||
    pickNonEmpty(appEnv, "SIGMARIS_CORE_URL") ||
    pickNonEmpty(repoEnv, "SIGMARIS_CORE_URL");
  const publicCoreUrl =
    pickNonEmpty(defaultVars, "NEXT_PUBLIC_SIGMARIS_CORE") ||
    pickNonEmpty(fileVars, "NEXT_PUBLIC_SIGMARIS_CORE") ||
    pickNonEmpty(appEnv, "NEXT_PUBLIC_SIGMARIS_CORE") ||
    pickNonEmpty(repoEnv, "NEXT_PUBLIC_SIGMARIS_CORE");
  const autoBrowse =
    pickNonEmpty(defaultVars, "TOUHOU_AUTO_BROWSE_ENABLED") ||
    pickNonEmpty(fileVars, "TOUHOU_AUTO_BROWSE_ENABLED") ||
    pickNonEmpty(appEnv, "TOUHOU_AUTO_BROWSE_ENABLED") ||
    pickNonEmpty(repoEnv, "TOUHOU_AUTO_BROWSE_ENABLED");
  const uploadEnabled =
    pickNonEmpty(defaultVars, "TOUHOU_UPLOAD_ENABLED") ||
    pickNonEmpty(fileVars, "TOUHOU_UPLOAD_ENABLED") ||
    pickNonEmpty(appEnv, "TOUHOU_UPLOAD_ENABLED") ||
    pickNonEmpty(repoEnv, "TOUHOU_UPLOAD_ENABLED");

  const setIfEmpty = (k, v) => {
    const cur = String(mergedEnv[k] ?? "").trim();
    const next = String(v ?? "").trim();
    if (!next) return;
    if (cur) return;
    mergedEnv[k] = next;
  };
  const setIfEmptyOrTemplateDefault = (k, v, templateDefault) => {
    const cur = String(mergedEnv[k] ?? "").trim();
    const next = String(v ?? "").trim();
    if (!next) return;
    if (!cur || cur === String(templateDefault ?? "").trim()) mergedEnv[k] = next;
  };

  // Bundled defaults are highest priority in desktop dev, too.
  if (supabaseUrl) mergedEnv.SUPABASE_URL = supabaseUrl;
  if (supabaseAnon) mergedEnv.SUPABASE_ANON_KEY = supabaseAnon;
  if (coreUrl) mergedEnv.SIGMARIS_CORE_URL = coreUrl;
  if (publicCoreUrl) mergedEnv.NEXT_PUBLIC_SIGMARIS_CORE = publicCoreUrl;
  setIfEmpty("TOUHOU_AUTO_BROWSE_ENABLED", autoBrowse);
  setIfEmpty("TOUHOU_UPLOAD_ENABLED", uploadEnabled);

  // Explicitly drop service role (do not load it from userData env file).
  delete mergedEnv.SUPABASE_SERVICE_ROLE_KEY;

  const desktopEnv = {
    ...mergedEnv,
    TOUHOU_DESKTOP_USERDATA_DIR: userDataDir,
    TOUHOU_DESKTOP_ENV_PATH: envPath,
    TOUHOU_DESKTOP_DEV_URL: `http://127.0.0.1:${port}`,
  };

  // Small diagnostics to avoid "why is login broken" mysteries.
  console.log(`[desktop:dev] userDataDir: ${userDataDir}`);
  console.log(`[desktop:dev] envPath: ${envPath}`);
  console.log(
    `[desktop:dev] supabase public env: url=${desktopEnv.NEXT_PUBLIC_SUPABASE_URL ? "OK" : "MISSING"} anon=${
      desktopEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY ? "OK" : "MISSING"
    }`,
  );
  console.log(
    `[desktop:dev] sigmaris core: ${desktopEnv.SIGMARIS_CORE_URL ? desktopEnv.SIGMARIS_CORE_URL : "MISSING"}`,
  );

  const nextProc = spawn(process.execPath, [devScript, "--port", String(port)], {
    cwd: projectRoot,
    env: desktopEnv,
    stdio: "inherit",
  });

  const cleanup = () => {
    try {
      if (!nextProc.killed) nextProc.kill();
    } catch {}
  };
  process.on("exit", cleanup);
  process.on("SIGINT", () => process.exit(130));
  process.on("SIGTERM", () => process.exit(143));

  nextProc.on("exit", (code) => {
    process.exit(code ?? 1);
  });

  const ok = await waitForHttpOk(`http://127.0.0.1:${port}/entry`, 30000);
  if (!ok) {
    console.error(`[desktop:dev] Next dev server did not respond on http://127.0.0.1:${port}`);
    process.exit(1);
  }

  if (String(process.env.TOUHOU_DESKTOP_DEV_NO_ELECTRON ?? "").trim() === "1") {
    console.log("[desktop:dev] TOUHOU_DESKTOP_DEV_NO_ELECTRON=1; stopping after Next dev boot check");
    try {
      if (!nextProc.killed) nextProc.kill();
    } catch {}
    process.exit(0);
  }

  const electronProc = spawn(electronBin, [electronMain], {
    cwd: projectRoot,
    env: desktopEnv,
    stdio: "inherit",
  });

  electronProc.on("exit", (code) => {
    try {
      if (!nextProc.killed) nextProc.kill();
    } catch {}
    process.exit(code ?? 0);
  });
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
