-- World localization patch: Japanese master labels (fully curated)

update public.world_characters set name = '稗田 阿求', title = '御阿礼の子', updated_at = now() where world_id = 'gensokyo_main' and id = 'akyuu';
update public.world_characters set name = 'アリス・マーガトロイド', title = '七色の人形遣い', updated_at = now() where world_id = 'gensokyo_main' and id = 'alice';
update public.world_characters set name = '高麗野 あうん', title = '神社を守る狛犬', updated_at = now() where world_id = 'gensokyo_main' and id = 'aunn';
update public.world_characters set name = '射命丸 文', title = '伝統の幻想ブン屋', updated_at = now() where world_id = 'gensokyo_main' and id = 'aya';
update public.world_characters set name = '九十九 弁々', title = '琵琶の付喪神', updated_at = now() where world_id = 'gensokyo_main' and id = 'benben';
update public.world_characters set name = '孫 美天', title = '花果子念報の闘士', updated_at = now() where world_id = 'gensokyo_main' and id = 'biten';
update public.world_characters set name = '聖 白蓮', title = '命蓮寺の住職', updated_at = now() where world_id = 'gensokyo_main' and id = 'byakuren';
update public.world_characters set name = '橙', title = '凶兆の黒猫', updated_at = now() where world_id = 'gensokyo_main' and id = 'chen';
update public.world_characters set name = '天弓 千亦', title = '市場を司る神', updated_at = now() where world_id = 'gensokyo_main' and id = 'chimata';
update public.world_characters set name = '天火人 ちやり', title = '血の池地獄の案内役', updated_at = now() where world_id = 'gensokyo_main' and id = 'chiyari';
update public.world_characters set name = 'チルノ', title = '氷の妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'cirno';
update public.world_characters set name = 'クラウンピース', title = '地獄の妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'clownpiece';
update public.world_characters set name = 'ドレミー・スイート', title = '夢の支配者', updated_at = now() where world_id = 'gensokyo_main' and id = 'doremy';
update public.world_characters set name = '戎 瓔花', title = '積み石の河原の亡霊', updated_at = now() where world_id = 'gensokyo_main' and id = 'eika';
update public.world_characters set name = '四季映姫・ヤマザナドゥ', title = '楽園の最高裁判長', updated_at = now() where world_id = 'gensokyo_main' and id = 'eiki';
update public.world_characters set name = '八意 永琳', title = '月の頭脳', updated_at = now() where world_id = 'gensokyo_main' and id = 'eirin';
update public.world_characters set name = '三頭 慧ノ子', title = '狼組の頭領', updated_at = now() where world_id = 'gensokyo_main' and id = 'enoko';
update public.world_characters set name = 'エタニティラルバ', title = '真夏の蝶の妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'eternity';
update public.world_characters set name = 'フランドール・スカーレット', title = '紅魔館のもう一人の主', updated_at = now() where world_id = 'gensokyo_main' and id = 'flandre';
update public.world_characters set name = '物部 布都', title = '古代の道士', updated_at = now() where world_id = 'gensokyo_main' and id = 'futo';
update public.world_characters set name = '姫海棠 はたて', title = '流行を追う天狗記者', updated_at = now() where world_id = 'gensokyo_main' and id = 'hatate';
update public.world_characters set name = 'ヘカーティア・ラピスラズリ', title = '多元世界の女神', updated_at = now() where world_id = 'gensokyo_main' and id = 'hecatia';
update public.world_characters set name = '鍵山 雛', title = '厄の女神', updated_at = now() where world_id = 'gensokyo_main' and id = 'hina';
update public.world_characters set name = '豫母都 日狭美', title = '黄泉へ誘う案内人', updated_at = now() where world_id = 'gensokyo_main' and id = 'hisami';
update public.world_characters set name = '雲居 一輪', title = '入道使いの尼僧', updated_at = now() where world_id = 'gensokyo_main' and id = 'ichirin';
update public.world_characters set name = '永江 衣玖', title = '竜宮の使い遊泳弾', updated_at = now() where world_id = 'gensokyo_main' and id = 'iku';
update public.world_characters set name = '依神 女苑', title = '浪費を呼ぶ疫病神', updated_at = now() where world_id = 'gensokyo_main' and id = 'joon';
update public.world_characters set name = '純狐', title = '純化された怨念', updated_at = now() where world_id = 'gensokyo_main' and id = 'junko';
update public.world_characters set name = '今泉 影狼', title = '竹林の狼人', updated_at = now() where world_id = 'gensokyo_main' and id = 'kagerou';
update public.world_characters set name = '蓬莱山 輝夜', title = '永遠と須臾の姫君', updated_at = now() where world_id = 'gensokyo_main' and id = 'kaguya';
update public.world_characters set name = '八坂 神奈子', title = '山と湖の化身', updated_at = now() where world_id = 'gensokyo_main' and id = 'kanako';
update public.world_characters set name = '茨木 華扇', title = '片腕有角の仙人', updated_at = now() where world_id = 'gensokyo_main' and id = 'kasen';
update public.world_characters set name = '埴安神 袿姫', title = '偶像を創る神', updated_at = now() where world_id = 'gensokyo_main' and id = 'keiki';
update public.world_characters set name = '上白沢 慧音', title = '歴史を喰らう半獣', updated_at = now() where world_id = 'gensokyo_main' and id = 'keine';
update public.world_characters set name = 'キスメ', title = '桶に潜む井戸妖怪', updated_at = now() where world_id = 'gensokyo_main' and id = 'kisume';
update public.world_characters set name = '多々良 小傘', title = '愉快な忘れ傘', updated_at = now() where world_id = 'gensokyo_main' and id = 'kogasa';
update public.world_characters set name = '古明地 こいし', title = '閉じた恋の瞳', updated_at = now() where world_id = 'gensokyo_main' and id = 'koishi';
update public.world_characters set name = '秦 こころ', title = '感情豊かなポーカーフェイス', updated_at = now() where world_id = 'gensokyo_main' and id = 'kokoro';
update public.world_characters set name = '小野塚 小町', title = '三途の水先案内人', updated_at = now() where world_id = 'gensokyo_main' and id = 'komachi';
update public.world_characters set name = '本居 小鈴', title = '鈴奈庵の看板娘', updated_at = now() where world_id = 'gensokyo_main' and id = 'kosuzu';
update public.world_characters set name = '庭渡 久侘歌', title = '地獄の関所を守る神', updated_at = now() where world_id = 'gensokyo_main' and id = 'kutaka';
update public.world_characters set name = '幽谷 響子', title = '山彦の僧侶', updated_at = now() where world_id = 'gensokyo_main' and id = 'kyouko';
update public.world_characters set name = 'レティ・ホワイトロック', title = '冬の忘れ物', updated_at = now() where world_id = 'gensokyo_main' and id = 'letty';
update public.world_characters set name = 'リリーホワイト', title = '春を告げる妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'lily_white';
update public.world_characters set name = 'ルナチャイルド', title = '静寂の妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'luna_child';
update public.world_characters set name = 'ルナサ・プリズムリバー', title = '騒霊ヴァイオリニスト', updated_at = now() where world_id = 'gensokyo_main' and id = 'lunasa';
update public.world_characters set name = 'リリカ・プリズムリバー', title = '騒霊キーボーディスト', updated_at = now() where world_id = 'gensokyo_main' and id = 'lyrica';
update public.world_characters set name = '丁礼田 舞', title = '後戸で舞う従者', updated_at = now() where world_id = 'gensokyo_main' and id = 'mai';
update public.world_characters set name = '二ッ岩 マミゾウ', title = '古参の化け狸', updated_at = now() where world_id = 'gensokyo_main' and id = 'mamizou';
update public.world_characters set name = '霧雨 魔理沙', title = '普通の魔法使い', updated_at = now() where world_id = 'gensokyo_main' and id = 'marisa';
update public.world_characters set name = '杖刀偶 磨弓', title = '埴輪の武人', updated_at = now() where world_id = 'gensokyo_main' and id = 'mayumi';
update public.world_characters set name = 'メディスン・メランコリー', title = '小さなスイートポイズン', updated_at = now() where world_id = 'gensokyo_main' and id = 'medicine';
update public.world_characters set name = '飯綱丸 龍', title = '大天狗の長', updated_at = now() where world_id = 'gensokyo_main' and id = 'megumu';
update public.world_characters set name = '紅 美鈴', title = '華人小娘', updated_at = now() where world_id = 'gensokyo_main' and id = 'meiling';
update public.world_characters set name = 'メルラン・プリズムリバー', title = '騒霊トランペッター', updated_at = now() where world_id = 'gensokyo_main' and id = 'merlin';
update public.world_characters set name = '豪徳寺 ミケ', title = '招福の白猫', updated_at = now() where world_id = 'gensokyo_main' and id = 'mike';
update public.world_characters set name = '豊聡耳 神子', title = '聖徳道士', updated_at = now() where world_id = 'gensokyo_main' and id = 'miko';
update public.world_characters set name = '秋 穣子', title = '豊穣の神', updated_at = now() where world_id = 'gensokyo_main' and id = 'minoriko';
update public.world_characters set name = '玉造 魅須丸', title = '勾玉職人', updated_at = now() where world_id = 'gensokyo_main' and id = 'misumaru';
update public.world_characters set name = '奥野田 美宵', title = '酔いどれの看板娘', updated_at = now() where world_id = 'gensokyo_main' and id = 'miyoi';
update public.world_characters set name = '宮出口 瑞霊', title = '祟りを秘めた怨霊', updated_at = now() where world_id = 'gensokyo_main' and id = 'mizuchi';
update public.world_characters set name = '藤原 妹紅', title = '蓬莱の人の形', updated_at = now() where world_id = 'gensokyo_main' and id = 'mokou';
update public.world_characters set name = '犬走 椛', title = '山の天狗の見張り番', updated_at = now() where world_id = 'gensokyo_main' and id = 'momiji';
update public.world_characters set name = '姫虫 百々世', title = '龍を食らう大百足', updated_at = now() where world_id = 'gensokyo_main' and id = 'momoyo';
update public.world_characters set name = '村紗 水蜜', title = '愉快な忘れ傘', updated_at = now() where world_id = 'gensokyo_main' and id = 'murasa';
update public.world_characters set name = 'ミスティア・ローレライ', title = '夜雀の妖怪', updated_at = now() where world_id = 'gensokyo_main' and id = 'mystia';
update public.world_characters set name = '矢田寺 成美', title = '魔法地蔵', updated_at = now() where world_id = 'gensokyo_main' and id = 'narumi';
update public.world_characters set name = 'ナズーリン', title = 'ダウザーの小さな大将', updated_at = now() where world_id = 'gensokyo_main' and id = 'nazrin';
update public.world_characters set name = '坂田 ネムノ', title = '近代の山姥', updated_at = now() where world_id = 'gensokyo_main' and id = 'nemuno';
update public.world_characters set name = '河城 にとり', title = '超妖怪弾頭', updated_at = now() where world_id = 'gensokyo_main' and id = 'nitori';
update public.world_characters set name = '封獣 ぬえ', title = '正体不明の妖怪', updated_at = now() where world_id = 'gensokyo_main' and id = 'nue';
update public.world_characters set name = '摩多羅 隠岐奈', title = '秘神', updated_at = now() where world_id = 'gensokyo_main' and id = 'okina';
update public.world_characters set name = '水橋 パルスィ', title = '地殻の下の嫉妬心', updated_at = now() where world_id = 'gensokyo_main' and id = 'parsee';
update public.world_characters set name = 'パチュリー・ノーレッジ', title = '知識と日陰の少女', updated_at = now() where world_id = 'gensokyo_main' and id = 'patchouli';
update public.world_characters set name = '堀川 雷鼓', title = '夢幻のパーカッショニスト', updated_at = now() where world_id = 'gensokyo_main' and id = 'raiko';
update public.world_characters set name = '八雲 藍', title = 'すきま妖怪の式', updated_at = now() where world_id = 'gensokyo_main' and id = 'ran';
update public.world_characters set name = '博麗 霊夢', title = '楽園の巫女', updated_at = now() where world_id = 'gensokyo_main' and id = 'reimu';
update public.world_characters set name = '鈴仙・優曇華院・イナバ', title = '狂気の月の兎', updated_at = now() where world_id = 'gensokyo_main' and id = 'reisen';
update public.world_characters set name = 'レミリア・スカーレット', title = '永遠に紅い幼き月', updated_at = now() where world_id = 'gensokyo_main' and id = 'remilia';
update public.world_characters set name = '火焔猫 燐', title = '地獄の輪禍', updated_at = now() where world_id = 'gensokyo_main' and id = 'rin';
update public.world_characters set name = '鈴瑚', title = '団子を食べる月の兎', updated_at = now() where world_id = 'gensokyo_main' and id = 'ringo';
update public.world_characters set name = '森近 霖之助', title = '独自理論の道具屋', updated_at = now() where world_id = 'gensokyo_main' and id = 'rinnosuke';
update public.world_characters set name = 'ルーミア', title = '宵闇の妖怪', updated_at = now() where world_id = 'gensokyo_main' and id = 'rumia';
update public.world_characters set name = '稀神 サグメ', title = '片翼の白鷺', updated_at = now() where world_id = 'gensokyo_main' and id = 'sagume';
update public.world_characters set name = '驪駒 早鬼', title = '地獄の最高速ライダー', updated_at = now() where world_id = 'gensokyo_main' and id = 'saki';
update public.world_characters set name = '十六夜 咲夜', title = '完全で瀟洒な従者', updated_at = now() where world_id = 'gensokyo_main' and id = 'sakuya';
update public.world_characters set name = '東風谷 早苗', title = '祀られる風の人間', updated_at = now() where world_id = 'gensokyo_main' and id = 'sanae';
update public.world_characters set name = '駒草 山如', title = '山の煙草商', updated_at = now() where world_id = 'gensokyo_main' and id = 'sannyo';
update public.world_characters set name = '爾子田 里乃', title = '後戸の扉を開く従者', updated_at = now() where world_id = 'gensokyo_main' and id = 'satono';
update public.world_characters set name = '古明地 さとり', title = 'みんなの心を読む妖怪', updated_at = now() where world_id = 'gensokyo_main' and id = 'satori';
update public.world_characters set name = '霍 青娥', title = '壁抜けの邪仙', updated_at = now() where world_id = 'gensokyo_main' and id = 'seiga';
update public.world_characters set name = '鬼人 正邪', title = '逆襲のあまのじゃく', updated_at = now() where world_id = 'gensokyo_main' and id = 'seija';
update public.world_characters set name = '清蘭', title = '浅葱色のイーグルラヴィ', updated_at = now() where world_id = 'gensokyo_main' and id = 'seiran';
update public.world_characters set name = '赤蛮奇', title = 'ろくろ首の怪奇', updated_at = now() where world_id = 'gensokyo_main' and id = 'sekibanki';
update public.world_characters set name = '少名 針妙丸', title = '小人の末裔', updated_at = now() where world_id = 'gensokyo_main' and id = 'shinmyoumaru';
update public.world_characters set name = '依神 紫苑', title = '最凶最悪の双子の妹', updated_at = now() where world_id = 'gensokyo_main' and id = 'shion';
update public.world_characters set name = '秋 静葉', title = '寂しさと終焉の象徴', updated_at = now() where world_id = 'gensokyo_main' and id = 'shizuha';
update public.world_characters set name = '寅丸 星', title = '毘沙門天の弟子', updated_at = now() where world_id = 'gensokyo_main' and id = 'shou';
update public.world_characters set name = 'スターサファイア', title = '星の光の妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'star_sapphire';
update public.world_characters set name = '伊吹 萃香', title = '伊吹の萃香', updated_at = now() where world_id = 'gensokyo_main' and id = 'suika';
update public.world_characters set name = '宇佐見 菫子', title = '超能力を操る高校生', updated_at = now() where world_id = 'gensokyo_main' and id = 'sumireko';
update public.world_characters set name = 'サニーミルク', title = '日光の妖精', updated_at = now() where world_id = 'gensokyo_main' and id = 'sunny_milk';
update public.world_characters set name = '洩矢 諏訪子', title = '土着神の頂点', updated_at = now() where world_id = 'gensokyo_main' and id = 'suwako';
update public.world_characters set name = '山城 たかね', title = '山奥のビジネス妖怪', updated_at = now() where world_id = 'gensokyo_main' and id = 'takane';
update public.world_characters set name = '比那名居 天子', title = '非想非非想天の娘', updated_at = now() where world_id = 'gensokyo_main' and id = 'tenshi';
update public.world_characters set name = '因幡 てゐ', title = '幸運の素兎', updated_at = now() where world_id = 'gensokyo_main' and id = 'tewi';
update public.world_characters set name = '蘇我 屠自古', title = '入鹿の雷', updated_at = now() where world_id = 'gensokyo_main' and id = 'tojiko';
update public.world_characters set name = '綿月 豊姫', title = '山海の豊姫', updated_at = now() where world_id = 'gensokyo_main' and id = 'toyohime';
update public.world_characters set name = '菅牧 典', title = '高貴なる策謀家', updated_at = now() where world_id = 'gensokyo_main' and id = 'tsukasa';
update public.world_characters set name = '牛崎 潤美', title = '水没した沈愁地獄', updated_at = now() where world_id = 'gensokyo_main' and id = 'urumi';
update public.world_characters set name = '霊烏路 空', title = '熱かい悩む神の火', updated_at = now() where world_id = 'gensokyo_main' and id = 'utsuho';
update public.world_characters set name = 'わかさぎ姫', title = '秘境の人魚', updated_at = now() where world_id = 'gensokyo_main' and id = 'wakasagihime';
update public.world_characters set name = 'リグル・ナイトバグ', title = '蠢く光の蟲', updated_at = now() where world_id = 'gensokyo_main' and id = 'wriggle';
update public.world_characters set name = '吉弔 八千慧', title = '鬼傑組組長', updated_at = now() where world_id = 'gensokyo_main' and id = 'yachie';
update public.world_characters set name = '黒谷 ヤマメ', title = '暗い洞窟の明るい網', updated_at = now() where world_id = 'gensokyo_main' and id = 'yamame';
update public.world_characters set name = '九十九 八橋', title = '古びた琴の付喪神', updated_at = now() where world_id = 'gensokyo_main' and id = 'yatsuhashi';
update public.world_characters set name = '綿月 依姫', title = '神霊に取り憑かれた月の姫', updated_at = now() where world_id = 'gensokyo_main' and id = 'yorihime';
update public.world_characters set name = '宮古 芳香', title = '忠実なキョンシー', updated_at = now() where world_id = 'gensokyo_main' and id = 'yoshika';
update public.world_characters set name = '魂魄 妖夢', title = '半人半霊の庭師', updated_at = now() where world_id = 'gensokyo_main' and id = 'youmu';
update public.world_characters set name = '八雲 紫', title = '神隠しの主犯', updated_at = now() where world_id = 'gensokyo_main' and id = 'yukari';
update public.world_characters set name = '星熊 勇儀', title = '語られる怪力乱神', updated_at = now() where world_id = 'gensokyo_main' and id = 'yuugi';
update public.world_characters set name = '風見 幽香', title = '四季のフラワーマスター', updated_at = now() where world_id = 'gensokyo_main' and id = 'yuuka';
update public.world_characters set name = '饕餮 尤魔', title = '強欲な獣の霊', updated_at = now() where world_id = 'gensokyo_main' and id = 'yuuma';
update public.world_characters set name = '西行寺 幽々子', title = '華胥の亡霊', updated_at = now() where world_id = 'gensokyo_main' and id = 'yuyuko';
update public.world_characters set name = '日白 残無', title = '無の獄王', updated_at = now() where world_id = 'gensokyo_main' and id = 'zanmu';

update public.world_locations set name = '後戸の国', updated_at = now() where world_id = 'gensokyo_main' and id = 'backdoor_realm';
update public.world_locations set name = '迷いの竹林', updated_at = now() where world_id = 'gensokyo_main' and id = 'bamboo_forest';
update public.world_locations set name = '竹林の小径', updated_at = now() where world_id = 'gensokyo_main' and id = 'bamboo_path';
update public.world_locations set name = '畜生界', updated_at = now() where world_id = 'gensokyo_main' and id = 'beast_realm';
update public.world_locations set name = '有頂天', updated_at = now() where world_id = 'gensokyo_main' and id = 'bhavaagra';
update public.world_locations set name = '血の池地獄', updated_at = now() where world_id = 'gensokyo_main' and id = 'blood_pool_hell';
update public.world_locations set name = '地霊殿', updated_at = now() where world_id = 'gensokyo_main' and id = 'chireiden';
update public.world_locations set name = '神霊廟', updated_at = now() where world_id = 'gensokyo_main' and id = 'divine_spirit_mausoleum';
update public.world_locations set name = '夢の世界', updated_at = now() where world_id = 'gensokyo_main' and id = 'dream_world';
update public.world_locations set name = '永遠亭', updated_at = now() where world_id = 'gensokyo_main' and id = 'eientei';
update public.world_locations set name = '魔法の森', updated_at = now() where world_id = 'gensokyo_main' and id = 'forest_of_magic';
update public.world_locations set name = '旧地獄', updated_at = now() where world_id = 'gensokyo_main' and id = 'former_hell';
update public.world_locations set name = '玄武の沢', updated_at = now() where world_id = 'gensokyo_main' and id = 'genbu_ravine';
update public.world_locations set name = '白玉楼', updated_at = now() where world_id = 'gensokyo_main' and id = 'hakugyokurou';
update public.world_locations set name = '博麗神社', updated_at = now() where world_id = 'gensokyo_main' and id = 'hakurei_shrine';
update public.world_locations set name = '天界', updated_at = now() where world_id = 'gensokyo_main' and id = 'heaven';
update public.world_locations set name = '人里', updated_at = now() where world_id = 'gensokyo_main' and id = 'human_village';
update public.world_locations set name = '河童工房', updated_at = now() where world_id = 'gensokyo_main' and id = 'kappa_workshop';
update public.world_locations set name = '香霖堂', updated_at = now() where world_id = 'gensokyo_main' and id = 'kourindou';
update public.world_locations set name = '月の都', updated_at = now() where world_id = 'gensokyo_main' and id = 'lunar_capital';
update public.world_locations set name = '紅魔館図書館', updated_at = now() where world_id = 'gensokyo_main' and id = 'mansion_library';
update public.world_locations set name = '霧の湖', updated_at = now() where world_id = 'gensokyo_main' and id = 'misty_lake';
update public.world_locations set name = '守矢神社', updated_at = now() where world_id = 'gensokyo_main' and id = 'moriya_shrine';
update public.world_locations set name = '守矢神社 上社', updated_at = now() where world_id = 'gensokyo_main' and id = 'moriya_upper_precinct';
update public.world_locations set name = '無縁塚', updated_at = now() where world_id = 'gensokyo_main' and id = 'muenzuka';
update public.world_locations set name = '命蓮寺', updated_at = now() where world_id = 'gensokyo_main' and id = 'myouren_temple';
update public.world_locations set name = '無名の丘', updated_at = now() where world_id = 'gensokyo_main' and id = 'nameless_hill';
update public.world_locations set name = '冥界', updated_at = now() where world_id = 'gensokyo_main' and id = 'netherworld';
update public.world_locations set name = '旧都', updated_at = now() where world_id = 'gensokyo_main' and id = 'old_capital';
update public.world_locations set name = '虹龍洞', updated_at = now() where world_id = 'gensokyo_main' and id = 'rainbow_dragon_cave';
update public.world_locations set name = '三途の川', updated_at = now() where world_id = 'gensokyo_main' and id = 'sanzu_river';
update public.world_locations set name = '紅魔館', updated_at = now() where world_id = 'gensokyo_main' and id = 'scarlet_devil_mansion';
update public.world_locations set name = '紅魔館の門', updated_at = now() where world_id = 'gensokyo_main' and id = 'scarlet_gate';
update public.world_locations set name = '仙界', updated_at = now() where world_id = 'gensokyo_main' and id = 'senkai';
update public.world_locations set name = '輝針城', updated_at = now() where world_id = 'gensokyo_main' and id = 'shining_needle_castle';
update public.world_locations set name = '鈴奈庵', updated_at = now() where world_id = 'gensokyo_main' and id = 'suzunaan';
update public.world_locations set name = '妖怪の山の麓', updated_at = now() where world_id = 'gensokyo_main' and id = 'youkai_mountain_foot';
