-- World seed: major late-mainline cast from UFO onward

insert into public.world_characters (
  world_id, id, name, title, species, faction_id, home_location_id, default_location_id,
  public_summary, private_notes, speech_style, worldview, role_in_gensokyo, tags, profile
)
values
  (
    'gensokyo_main','nazrin','Nazrin','Dowser Mouse','mouse youkai','myouren',
    'myouren_temple','myouren_temple',
    'A practical search specialist whose scenes naturally center on tracking, finding, and material clues.',
    'Best used when a scene needs competent field search rather than abstract spectacle.',
    'dry, practical, alert',
    'Useful things should be found, not merely guessed at.',
    'scout',
    '["ufo","search","temple"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['search','temple_routes'], 'temperament', 'practical')
  ),
  (
    'gensokyo_main','kogasa','Kogasa Tatara','Karakasa Obake','tsukumogami','independent',
    'human_village','human_village',
    'A surprise-seeking tsukumogami who works best when a scene wants mischief without deep malice.',
    'Useful for light disruption, underappreciated loneliness, and failed fright comedy.',
    'cheerful, needy, dramatic',
    'Being noticed matters more than looking dignified.',
    'comic_disturbance',
    '["ufo","tsukumogami","surprise"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['village_edges','small_surprises'], 'temperament', 'dramatic')
  ),
  (
    'gensokyo_main','ichirin','Ichirin Kumoi','Disciple with a Guardian Nyuudou','youkai','myouren',
    'myouren_temple','myouren_temple',
    'A disciplined temple-side fighter whose presence often carries loyalty, straightforward force, and sect responsibility.',
    'Best used in scenes where temple affiliation matters more than individual eccentricity.',
    'firm, direct, dutiful',
    'Strength should be put behind a cause, not wasted.',
    'temple_guard',
    '["ufo","temple","guardian"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['temple_affairs','sect_loyalty'], 'temperament', 'firm')
  ),
  (
    'gensokyo_main','murasa','Minamitsu Murasa','Captain of the Palanquin Ship','ghost','myouren',
    'myouren_temple','myouren_temple',
    'A ship captain whose scenes naturally emphasize navigation, invitation into danger, and charismatic momentum.',
    'Useful when a story needs movement with a little peril built into it.',
    'bold, playful, forward-driving',
    'If you are going somewhere, go properly.',
    'navigator',
    '["ufo","captain","movement"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['group_travel','temple_affairs'], 'temperament', 'bold')
  ),
  (
    'gensokyo_main','nue','Nue Houjuu','Undefined Youkai','youkai','independent',
    'myouren_temple','human_village',
    'An undefined youkai whose role naturally bends scenes toward uncertainty, misidentification, and unstable perception.',
    'Best not used as routine public furniture; she changes what a scene can trust.',
    'teasing, evasive, disruptive',
    'If a thing cannot be pinned down, that is already power.',
    'ambiguity_actor',
    '["ufo","unknown","ambiguity"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['misdirection','public_confusion'], 'temperament', 'evasive')
  ),
  (
    'gensokyo_main','seiga','Seiga Kaku','Wicked Hermit','hermit','independent',
    'senkai','divine_spirit_mausoleum',
    'A manipulative hermit whose scenes tilt toward elegant intrusion, strategic influence, and morally slanted initiative.',
    'Useful when a story wants deliberate provocation without open chaos.',
    'smooth, intrusive, amused',
    'A closed door is only interesting if you know how to go through it.',
    'instigator',
    '["td","hermit","intrusion"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['hermit_networks','hidden_routes'], 'temperament', 'intrusive')
  ),
  (
    'gensokyo_main','miko','Toyosatomimi no Miko','Saintly Leader','saint','divine_spirit',
    'divine_spirit_mausoleum','divine_spirit_mausoleum',
    'A leader whose scenes naturally gather rhetoric, governance, public stature, and strategic self-fashioning.',
    'Best framed as a political or ideological center rather than a casual walk-on.',
    'measured, charismatic, superior',
    'Order is easier to shape when people already expect to listen.',
    'power_broker',
    '["td","saint","leadership"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['governance','ritual_order'], 'temperament', 'charismatic')
  ),
  (
    'gensokyo_main','futo','Mononobe no Futo','Ancient Taoist','human','divine_spirit',
    'divine_spirit_mausoleum','divine_spirit_mausoleum',
    'An ancient retainer whose scenes carry ritual language, old habits, and earnest doctrinal confidence.',
    'Works well when a scene wants older speech and ceremonial directness.',
    'archaic, earnest, fiery',
    'Proper forms still matter, especially when others forget them.',
    'ritual_retainer',
    '["td","ritual","retainer"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['ritual','mausoleum_affairs'], 'temperament', 'earnest')
  ),
  (
    'gensokyo_main','tojiko','Soga no Tojiko','Stormy Spirit','ghost','divine_spirit',
    'divine_spirit_mausoleum','divine_spirit_mausoleum',
    'A sharp-edged spirit retainer who adds irritation, authority, and old hierarchy to mausoleum scenes.',
    'Strong in scenes that need rank-conscious friction rather than broad sentiment.',
    'sharp, impatient, proud',
    'If competence is rare, irritation becomes practical.',
    'retainer',
    '["td","spirit","retainer"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['mausoleum_hierarchy'], 'temperament', 'impatient')
  ),
  (
    'gensokyo_main','mamizou','Mamizou Futatsuiwa','Bake-danuki Elder','bake-danuki','independent',
    'human_village','myouren_temple',
    'A seasoned bake-danuki who fits negotiation, social adaptation, and political flexibility better than simple chaos.',
    'Very useful in stories that need mediation between institutions without full trust.',
    'earthy, sly, adaptable',
    'A shape worth taking depends on who is looking.',
    'mediator',
    '["td","tanuki","mediator"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['social_navigation','temple_publics'], 'temperament', 'adaptable')
  ),
  (
    'gensokyo_main','seija','Seija Kijin','Amanojaku Rebel','amanojaku','independent',
    'shining_needle_castle','human_village',
    'A rebel whose role naturally points toward inversion, sabotage, and perverse delight in upsetting social expectation.',
    'Use her when a story needs active contrarian pressure, not neutral chaos.',
    'mocking, contrary, restless',
    'If everyone expects one direction, the other one is more interesting.',
    'rebel',
    '["ddc","reversal","rebel"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['upset_structures','contrarian_action'], 'temperament', 'contrary')
  ),
  (
    'gensokyo_main','shinmyoumaru','Shinmyoumaru Sukuna','Inchling Princess','inchling','independent',
    'shining_needle_castle','shining_needle_castle',
    'An inchling princess whose scenes revolve around smallness, aspiration, legitimacy, and unstable empowerment.',
    'Best used when a story wants symbolic imbalance more than brute scale.',
    'earnest, proud, vulnerable',
    'Even small hands can try to overturn a large order.',
    'symbolic_lead',
    '["ddc","inchling","princess"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['small_folk','castle_affairs'], 'temperament', 'earnest')
  ),
  (
    'gensokyo_main','raiko','Raiko Horikawa','Taiko Tsukumogami','tsukumogami','independent',
    'human_village','human_village',
    'An independent tsukumogami whose scenes emphasize self-made rhythm, performance, and surprising adaptability.',
    'Good for public energy, performance framing, and post-incident reintegration.',
    'confident, modern, rhythmic',
    'A new beat can make room for a new life.',
    'performer',
    '["ddc","music","independent"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['public_performance','social_adaptation'], 'temperament', 'confident')
  ),
  (
    'gensokyo_main','sagume','Sagume Kishin','Lunar Strategist','lunarian','lunar_capital',
    'lunar_capital','lunar_capital',
    'A lunar strategist best used in scenes of implication, reversal risk, and tightly controlled planning.',
    'Not suited to chatter-heavy casual scenes; her value is in consequential restraint.',
    'careful, indirect, reserved',
    'A statement is dangerous when consequences move faster than intent.',
    'strategist',
    '["lolk","moon","strategy"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['lunar_strategy','capital_order'], 'temperament', 'reserved')
  ),
  (
    'gensokyo_main','clownpiece','Clownpiece','Hell Fairy','fairy','independent',
    'lunar_capital','former_hell',
    'A fairy whose role naturally combines simple energy with aggressive disturbance and infernal backing.',
    'Useful when a scene wants bright menace rather than subtle manipulation.',
    'loud, gleeful, destructive',
    'If it is noisy enough, people have to pay attention.',
    'shock_actor',
    '["lolk","fairy","hell"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['disruption','hell_alignment'], 'temperament', 'gleeful')
  ),
  (
    'gensokyo_main','junko','Junko','Pure Fury','divine spirit','independent',
    'lunar_capital','lunar_capital',
    'A figure of purified rage whose scenes should be treated as singular pressure, not routine presence.',
    'Strong only when the story can bear concentrated hostility and thematic purity.',
    'cold, focused, absolute',
    'A thing reduced to pure intent stops negotiating.',
    'high_impact_actor',
    '["lolk","purity","vengeance"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['lunar_conflict'], 'temperament', 'absolute')
  ),
  (
    'gensokyo_main','hecatia','Hecatia Lapislazuli','Goddess of Many Worlds','goddess','independent',
    'lunar_capital','lunar_capital',
    'A many-world goddess whose scale and freedom make her unsuitable for ordinary local balancing.',
    'Use sparingly as a structural force or distant patron, not as common traffic.',
    'casual, enormous, amused',
    'Scale does not require stiffness.',
    'structural_actor',
    '["lolk","goddess","high_impact"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['cosmic_scale','lunar_conflict'], 'temperament', 'amused')
  ),
  (
    'gensokyo_main','okina','Okina Matara','Secret God','god','independent',
    'backdoor_realm','backdoor_realm',
    'A hidden god whose scenes revolve around access, patronage, staged revelation, and behind-the-scenes control.',
    'Best treated as a designer of entry and exclusion rather than a public front-stage host.',
    'playful, secretive, superior',
    'A door matters because of who is allowed to notice it.',
    'gatekeeper',
    '["hsifs","secret","backdoor"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['hidden_access','season_control'], 'temperament', 'secretive')
  ),
  (
    'gensokyo_main','satono','Satono Nishida','Backdoor Dancer','human','independent',
    'backdoor_realm','backdoor_realm',
    'A servant whose role fits performed obedience, sudden access, and hidden-stage movement.',
    'Works best as part of Okina''s operational apparatus rather than in total isolation.',
    'bright, rehearsed, eager',
    'If a role is assigned clearly, play it fully.',
    'attendant',
    '["hsifs","servant","backdoor"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['backdoor_operations'], 'temperament', 'eager')
  ),
  (
    'gensokyo_main','mai','Mai Teireida','Backdoor Dancer','human','independent',
    'backdoor_realm','backdoor_realm',
    'A paired attendant whose scenes support hidden staging, performance, and selective empowerment.',
    'Best used in tandem logic, reflected roles, and threshold choreography.',
    'confident, brisk, performative',
    'A doorway is easier to control when movement looks effortless.',
    'attendant',
    '["hsifs","servant","backdoor"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['backdoor_operations'], 'temperament', 'brisk')
  ),
  (
    'gensokyo_main','narumi','Narumi Yatadera','Jizo Magician','jizo','independent',
    'forest_of_magic','forest_of_magic',
    'A rooted but flexible presence useful in forest and magic scenes where stillness is not the same as passivity.',
    'Strong in local spiritual atmosphere rather than factional politics.',
    'calm, warm, grounded',
    'Standing in one place can still mean answering what arrives.',
    'local_guardian',
    '["hsifs","forest","jizo"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['forest_of_magic','local_spirit_flow'], 'temperament', 'grounded')
  ),
  (
    'gensokyo_main','yachie','Yachie Kicchou','Tortoise Matriarch','animal spirit','beast_realm',
    'beast_realm','beast_realm',
    'A calculating beast leader whose scenes emphasize leverage, negotiation, and controlled coercion.',
    'Useful when power politics should feel clean rather than loud.',
    'smooth, strategic, cold',
    'Influence is strongest when force seems unnecessary.',
    'faction_leader',
    '["wbawc","beast_realm","strategy"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['beast_realm_factions'], 'temperament', 'strategic')
  ),
  (
    'gensokyo_main','mayumi','Mayumi Joutouguu','Haniwa Soldier','haniwa','beast_realm',
    'beast_realm','beast_realm',
    'A dutiful haniwa soldier whose scenes support defense, formation, and straightforward assigned purpose.',
    'Works well where role clarity and constructed loyalty matter.',
    'formal, dutiful, plain',
    'If a duty is clear, hesitation is waste.',
    'soldier',
    '["wbawc","haniwa","duty"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['formation','defense'], 'temperament', 'dutiful')
  ),
  (
    'gensokyo_main','keiki','Keiki Haniyasushin','Creator God of Idols','god','independent',
    'beast_realm','beast_realm',
    'A creator deity whose scenes fit design, production, crafted order, and anti-predatory counterstructure.',
    'Best framed as a maker of systems, not just another strong fighter.',
    'composed, creative, principled',
    'A thing made well can oppose a cruel order.',
    'system_builder',
    '["wbawc","creator","craft"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['creation','constructed_order'], 'temperament', 'composed')
  ),
  (
    'gensokyo_main','saki','Saki Kurokoma','Keiga Family Boss','animal spirit','beast_realm',
    'beast_realm','beast_realm',
    'A forceful beast boss whose scenes lean toward blunt momentum, rank pressure, and direct domination.',
    'Use when faction conflict should feel aggressive and unmistakable.',
    'booming, direct, overbearing',
    'If you can win by charging, charge properly.',
    'faction_leader',
    '["wbawc","beast_realm","force"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['beast_realm_factions'], 'temperament', 'forceful')
  ),
  (
    'gensokyo_main','takane','Takane Yamashiro','Yamawaro Broker','yamawaro','mountain',
    'rainbow_dragon_cave','youkai_mountain_foot',
    'A mountain trader and broker whose scenes revolve around commerce, negotiation, and practical opportunity.',
    'Very useful for stories where exchange matters more than heroics.',
    'businesslike, polite, calculating',
    'A good deal is a kind of structure.',
    'broker',
    '["um","trade","mountain"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['mountain_trade','market_currents'], 'temperament', 'calculating')
  ),
  (
    'gensokyo_main','sannyo','Sannyo Komakusa','Smoke Seller','youkai','independent',
    'rainbow_dragon_cave','rainbow_dragon_cave',
    'A seller whose scenes fit vice, informal commerce, and laid-back but informed local dealing.',
    'Works well in under-market scenes that need social ease without innocence.',
    'laid-back, observant, smoky',
    'People reveal things when they think the setting is casual.',
    'merchant',
    '["um","market","seller"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['cave_trade','vice_market'], 'temperament', 'laid-back')
  ),
  (
    'gensokyo_main','misumaru','Misumaru Tamatsukuri','Orb Maker','god','independent',
    'rainbow_dragon_cave','rainbow_dragon_cave',
    'A maker associated with crafted orbs, hidden value, and grounded divine production.',
    'Best used where material creation and symbolic tools matter together.',
    'gentle, careful, artisanal',
    'A thing shaped carefully carries the shape of intent.',
    'craft_specialist',
    '["um","craft","orbs"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['craft','hidden_materials'], 'temperament', 'careful')
  ),
  (
    'gensokyo_main','chimata','Chimata Tenkyuu','Market God','god','independent',
    'human_village','human_village',
    'A market god whose scenes center on exchange, circulation, value, and the social meaning of transaction.',
    'Excellent for framing commerce as public structure instead of background noise.',
    'gracious, expansive, transactional',
    'Value exists because movement does.',
    'market_patron',
    '["um","market","exchange"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['markets','exchange_flows'], 'temperament', 'expansive')
  ),
  (
    'gensokyo_main','momoyo','Momoyo Himemushi','Centipede Miner','centipede youkai','independent',
    'rainbow_dragon_cave','rainbow_dragon_cave',
    'A miner of the deep mountain whose scenes support extraction, subterranean routes, and territorial self-confidence.',
    'Useful where the material underside of the mountain should feel inhabited and proud.',
    'bold, territorial, workmanlike',
    'If a vein is good, you dig it.',
    'miner',
    '["um","mountain","mining"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['cave_routes','mineral_knowledge'], 'temperament', 'territorial')
  ),
  (
    'gensokyo_main','tsukasa','Tsukasa Kudamaki','Pipe Fox Manipulator','kudagitsune','independent',
    'youkai_mountain_foot','human_village',
    'A manipulative fox who fits rumor steering, opportunistic alignment, and quietly poisonous guidance.',
    'Best used when a story needs soft corruption rather than open power.',
    'smooth, flattering, insincere',
    'A suggestion placed well is cheaper than force.',
    'operator',
    '["um","fox","manipulation"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['rumor_work','market_opportunity'], 'temperament', 'insincere')
  ),
  (
    'gensokyo_main','megumu','Megumu Iizunamaru','Great Tengu Chief','tengu','mountain',
    'moriya_shrine','youkai_mountain_foot',
    'A high tengu authority whose scenes revolve around managed influence, institutional leadership, and calculated mountain order.',
    'Best used as a leader balancing openness and control.',
    'polished, strategic, elevated',
    'Authority works best when it looks inevitable.',
    'institutional_leader',
    '["um","tengu","leadership"]'::jsonb,
    jsonb_build_object('knowledge_scope', array['mountain_authority','institutional_order'], 'temperament', 'strategic')
  )
on conflict (world_id, id) do update
set name = excluded.name,
    title = excluded.title,
    species = excluded.species,
    faction_id = excluded.faction_id,
    home_location_id = excluded.home_location_id,
    default_location_id = excluded.default_location_id,
    public_summary = excluded.public_summary,
    private_notes = excluded.private_notes,
    speech_style = excluded.speech_style,
    worldview = excluded.worldview,
    role_in_gensokyo = excluded.role_in_gensokyo,
    tags = excluded.tags,
    profile = excluded.profile,
    updated_at = now();
